### ISSUE TITLE
open source server side

### ISSUE THREAD

**Issue by TurBoss** [lolet/D2Ex2#12]
is there any interest in make it public?

at least me.

thanks

**Comment by jankowskib** [comment]
@TurBoss I gonna publish it as soon as I get some time to cleanup the repo

**Comment by TurBoss** [comment]
Awesome

Thank you!

**Comment by Mogelb4aum** [comment]
This sounds greate :)

Thx so much

**Comment by Mogelb4aum** [comment]
Any News ?

**Comment by jankowskib** [comment]
@Mogelb4aum here you are https://github.com/lolet/d2server

**Comment by TurBoss** [comment]
Thank you so much!!
