### ISSUE TITLE
error when launching the game and MULTIRES enabled

### ISSUE THREAD

**Issue by TurBoss** [lolet/D2Ex2#6]
Hi

I found this project amazing
making some test i found that when i enable MULTIRES in stdAfx.h
the game doesn't start and shows this popup

screenshots can be found here :

http://imgur.com/a/juxc4

thank you

**Comment by jankowskib** [comment]
Can you send me a pastebin with a D2XXXXXX.log file?

**Comment by TurBoss** [comment]
do you mean this? http://dpaste.com/3T4S720

I'm building the masterbranch from github not the release one
ty

**Comment by jankowskib** [comment]
Yeah...but there is no crash log inside ;( Try to run the game in window mode ( -w parameter)

**Comment by TurBoss** [comment]
is in window mode :S
same result

**Comment by jankowskib** [comment]
Send me the compiled D2Ex2.dll I'll check it l8r

**Comment by TurBoss** [comment]
here it is

https://mega.nz/#!EUgwAYQK

thank you so much

**Comment by TurBoss** [comment]
I have noticed that the link is bad :( sry 
here is the new one

https://mega.nz/#!EUgwAYQK!6jaDQlcIv4mb1M02hLKhxwZXapeQ-A-hD5KBTWDA310

**Comment by jankowskib** [comment]
Ouch, you still waiting 😄

**Comment by TurBoss** [comment]
not in a hurry just curious

thx

**Comment by jankowskib** [comment]
Just ran your DLL and it works fine. I can't do anything without the crash log

**Comment by TurBoss** [comment]
ok I will try to compile again and see what happends 

but i need to setup the build environment again (lost)
